import { createBattleView } from './battle-view.js';
const classes=[{name:'수호 기사',role:'탱커',icon:'♜',skill:'성역의 방패',desc:'도발과 보호막으로 파티를 지킵니다.',hp:1800,dps:17},{name:'철벽 전사',role:'탱커',icon:'⚒',skill:'불굴의 함성',desc:'강한 차단과 피해 반사에 특화됩니다.',hp:1600,dps:25},{name:'달빛 사제',role:'힐러',icon:'✧',skill:'정화의 빛',desc:'즉시 회복과 저주 해제에 특화됩니다.',hp:950,dps:8},{name:'숲의 치유사',role:'힐러',icon:'❧',skill:'생명의 숲',desc:'지속 회복으로 파티 전체를 돌봅니다.',hp:1100,dps:11},{name:'화염 마법사',role:'딜러',icon:'✹',skill:'유성 폭발',desc:'집중 공격 시 강력한 폭발 피해를 줍니다.',hp:900,dps:53},{name:'그림자 도적',role:'딜러',icon:'⚔',skill:'그림자 습격',desc:'빠른 차단과 근접 공격에 특화됩니다.',hp:1050,dps:47},{name:'바람 사냥꾼',role:'딜러',icon:'➶',skill:'관통 사격',desc:'원거리에서 소환된 적을 빠르게 처리합니다.',hp:1000,dps:45},{name:'폭풍 주술사',role:'딜러',icon:'ϟ',skill:'연쇄 번개',desc:'다수의 적에게 번개를 퍼뜨립니다.',hp:1050,dps:43},{name:'룬 검사',role:'딜러',icon:'✣',skill:'룬의 일격',desc:'방어막으로 버티며 꾸준히 공격합니다.',hp:1250,dps:39}];
const bosses=[{name:'몰락한 수호자',subtitle:'잿빛 성채의 문지기',hp:22000,color:'#bd7852',phases:['잠든 성채','깨어난 분노','최후의 맹세'],mechanics:['균열을 피하고 파멸의 포효를 차단하세요.','소환된 잿빛 망령을 우선 처리하세요.','광폭화 중 보호와 집중 공격을 활용하세요.']},{name:'가시의 여왕',subtitle:'잊힌 정원의 지배자',hp:25000,color:'#96a15d',phases:['독의 정원','가시의 부름','만개하는 죽음'],mechanics:['독 지대를 피하고 저주를 해제하세요.','가시 정령을 집중 공격으로 제거하세요.','빠른 독 폭발을 차단하고 회복을 유지하세요.']},{name:'공허의 감시자',subtitle:'별 없는 심연의 눈',hp:29000,color:'#a08bbd',phases:['공허의 시선','뒤틀린 현실','붕괴의 시간'],mechanics:['공허 광선을 피하고 붕괴를 차단하세요.','균열에서 나온 분신을 우선 처치하세요.','연속 광선을 피하며 마지막 힘을 집중하세요.']}];
let bi=0,selected=0,running=false,paused=false,speed=1,time=0,bhp=bosses[0].hp,phase=0,nextEvent=5,cast=null,zones=[],adds=[],fx=[],cool=[0,0,0,0],buff=0,shield=0,logs=[],toastUntil=0,last=performance.now(),won=false;
let party=[0,2,4,5,6].map((c,i)=>makeMember(c,i));
function makeMember(c,i){return{c,hp:classes[c].hp,x:[.5,.31,.25,.62,.76][i],y:[.51,.72,.58,.72,.59][i],tx:[.5,.31,.25,.62,.76][i],ty:[.51,.72,.58,.72,.59][i],debuff:0}};
const app=document.querySelector('#app');app.innerHTML=`<header><div class="brand"><span>♜</span>RAIDBOUND</div><nav><button class="active" id="raid-nav">레이드</button><button id="party-nav">파티 편성</button><button id="guide-nav">전투 가이드</button></nav><div class="profile"><span class="avatar">✧</span><span>원정대 지휘관<br><small class="small">잿빛 성채 · 첫 번째 원정</small></span></div></header><main><div class="crumb">원정 지도 / 잿빛 성채 <span>/ 보스 공략</span></div><div class="heading"><div><h1>잿빛 성채</h1><p>다섯 영웅, 하나의 운명. 당신의 판단이 전투를 바꿉니다.</p></div><span class="tag">5인 전술 레이드</span></div><div class="layout"><aside class="panel"><div class="panel-head"><span>당신의 파티</span><span class="small">1 탱커 · 1 힐러 · 3 딜러</span></div><div class="party-list" id="party"></div><div class="party-footer">✧ 함께 싸우는 다섯 영웅<br><span class="small">캐릭터 선택 → 영웅 시점으로 전환<br>편성은 전투 시작 전에 변경할 수 있습니다.</span></div></aside><section><div class="arena-panel"><div class="arena-top"><span class="live" id="status">출전 준비</span><span id="timer">00:00 / 04:00</span></div><div class="boss-hud"><div class="boss-name" id="boss-name"></div><div class="boss-sub" id="boss-sub"></div><div class="boss-bar"><i id="boss-fill"></i></div><div class="boss-health" id="boss-health"></div></div><div id="toast" class="toast hidden"></div><div class="canvas-wrap"><canvas id="arena"></canvas><div id="world-labels"></div><div class="camera-toolbar"><span id="camera-follow">카엘 시점 · 수호 기사</span><div><button id="camera-mode" title="전체 보기 / 영웅 추적">전체 보기</button><button id="camera-reset" title="카메라 초기화 [C]">C</button><button id="expand-view" title="전장 전체 화면">확대</button></div></div></div><div class="arena-caption"><div class="legend"><b><i></i>위험 범위</b><b><i></i>아군 / 보호</b></div><span>우클릭 회전 · 휠 확대 · C 시점 복귀</span></div></div><div class="arena-controls"><button class="button primary" id="start">▶ 전투 시작</button><button class="button" id="pause">Ⅱ 전술 일시정지 <small>[Space]</small></button><button class="speed" id="speed">1× 속도</button></div><div class="section-title"><span>지휘관 명령</span><span class="small">자동 공격 · 자동 회복 / 핵심 순간은 직접 지휘</span></div><div class="skills" id="skills"></div></section><aside class="panel right"><div><div class="panel-head"><span>보스 공략</span><span class="small">ENCOUNTER 0<span id="encounter">1</span></span></div><div class="right-content"><div id="phases"></div><div class="tip"><strong>✧ 지휘관의 전술 노트</strong><span id="tip">붉은 범위가 폭발하기 전에 회피하세요. 파멸의 포효는 차단이 필요합니다.</span></div><div class="boss-select" id="boss-select"></div></div></div><div class="log"><div class="panel-head"><span>전투 기록</span><span class="small">LIVE LOG</span></div><div class="right-content" id="logs"></div></div></aside></div><div class="bottom"><span>RAIDBOUND <span style="margin-left:12px">혼자 지휘하고, 함께 승리하세요.</span></span><span>1–5 시점 전환 · 방향키 이동 · Q 차단 · W 해제 · E 보호 · R 집중 · A 전체 회피</span></div></main><div id="modal-root"></div>`;
const canvas=document.querySelector('#arena');
let battle;
try {
  battle=createBattleView(canvas,{
    select(i){selected=i;renderParty()},
    move(x,y){party[selected].tx=x;party[selected].ty=y},
    cameraMode(overview){document.querySelector('#camera-mode').textContent=overview?'영웅 추적':'전체 보기'}
  });
} catch(error) {
  canvas.style.display='none';document.querySelector('.canvas-wrap').insertAdjacentHTML('beforeend','<div class="webgl-error">3D 전장을 시작할 수 없습니다.<br>브라우저의 하드웨어 가속을 켜고 최신 Chrome 또는 Edge로 다시 접속하세요.</div>');
  console.error(error);
}
const pressed=new Set();
window.addEventListener('keydown',e=>{if(document.querySelector('.overlay'))return;if(e.key.startsWith('Arrow')){e.preventDefault();pressed.add(e.key)}if(e.key.toLowerCase()==='c')battle?.center()});
window.addEventListener('keyup',e=>pressed.delete(e.key));
window.addEventListener('blur',()=>pressed.clear());
document.querySelector('#expand-view').onclick=()=>{const section=canvas.closest('section');if(document.fullscreenElement)document.exitFullscreen();else section.requestFullscreen().catch(()=>toast('이 브라우저는 전체 화면을 지원하지 않습니다.'))};
window.__raidbound={inspect:()=>({...battle?.inspect(),selected,time,paused,running,party:party.map(p=>({x:p.x,y:p.y,tx:p.tx,ty:p.ty,hp:p.hp}))}),screenPosition:i=>battle?.screenPosition(i)};

function log(msg,warn=false){logs.unshift({t:time,msg,warn});logs=logs.slice(0,5);document.querySelector('#logs').innerHTML=logs.map(l=>`<div class="log-row ${l.warn?'warning':''}"><span class="log-time">${fmt(l.t)}</span>${l.msg}</div>`).join('')}
function fmt(t){return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`}
function toast(msg){document.querySelector('#toast').textContent=msg;toastUntil=performance.now()+2400}
function renderParty(){document.querySelector('#party').innerHTML=party.map((p,i)=>{const c=classes[p.c];return `<div class="party-card ${i===selected?'selected':''}" data-member="${i}"><div class="member-top"><div class="portrait" style="--col:${p.c%4};--row:${Math.floor(p.c/4)};color:${['#acbfc0','#b9cc8b','#cfaf7a'][['탱커','힐러','딜러'].indexOf(c.role)]}"><span>${c.icon}</span></div><div><div class="name">${['카엘','엘리아','이그니스','레온','실바'][i]}</div><div class="class-label">${c.name}</div></div><span class="role">${c.role}</span></div><div class="hp"><i style="width:${Math.max(0,p.hp/c.hp*100)}%;background:${p.debuff?'#ad82bd':'#9cae82'}"></i></div><div class="member-bottom"><span>${Math.ceil(p.hp)} / ${c.hp}</span><span>${p.hp<=0?'전투 불능':p.debuff?'저주 · 해제 필요':'● '+(running?'전투 중':'준비 완료')}</span></div></div>`}).join('');document.querySelectorAll('[data-member]').forEach(el=>el.onclick=()=>{selected=+el.dataset.member;renderParty()})}
const commands=[['ϟ','공격 차단','포효 시전 중 사용','Q'],['✧','디버프 해제','저주 해제 + 회복','W'],['♜','파티 보호','8초간 피해 65% 감소','E'],['⚔','집중 공격','쫄 우선 · 8초 강화','R']];
function renderSkills(){document.querySelector('#skills').innerHTML=commands.map((s,i)=>`<button class="skill" data-skill="${i}" ${cool[i]>0||!running?'disabled':''}><span class="key">${s[3]}</span><div class="skill-icon">${s[0]}</div><div class="skill-name">${s[1]} ${cool[i]>0?Math.ceil(cool[i])+'s':''}</div><div class="skill-note">${s[2]}</div></button>`).join('');document.querySelectorAll('[data-skill]').forEach(el=>el.onclick=()=>command(+el.dataset.skill))}
function renderBoss(){const b=bosses[bi];document.querySelector('#boss-name').textContent=b.name;document.querySelector('#boss-sub').textContent=b.subtitle+' · PHASE '+(phase+1);document.querySelector('#boss-fill').style.width=bhp/b.hp*100+'%';document.querySelector('#boss-health').textContent=`${Math.ceil(bhp).toLocaleString()} / ${b.hp.toLocaleString()} HP`;document.querySelector('#phases').innerHTML=b.phases.map((p,i)=>`<div class="phase ${phase===i?'current':''}"><div class="phase-number">${i+1}</div><div><div class="phase-title">${p}</div><div class="phase-desc">${b.mechanics[i]}</div></div></div>`).join('');document.querySelector('#encounter').textContent=bi+1;document.querySelector('#boss-select').innerHTML=bosses.map((b,i)=>`<button data-boss="${i}" class="${bi===i?'active':''}">${['수호자','가시 여왕','감시자'][i]}</button>`).join('');document.querySelectorAll('[data-boss]').forEach(el=>el.onclick=()=>{if(running){toast('전투 종료 후 다른 보스를 선택하세요.');return}bi=+el.dataset.boss;reset()})}
function reset(){running=false;paused=false;won=false;time=0;phase=0;bhp=bosses[bi].hp;nextEvent=5;cast=null;zones=[];adds=[];fx=[];cool=[0,0,0,0];buff=shield=0;document.querySelector('#pause').innerHTML='Ⅱ 전술 일시정지 <small>[Space]</small>';document.querySelector('#tip').textContent=bosses[bi].mechanics[0];party=party.map((p,i)=>makeMember(p.c,i));logs=[];log('파티가 성채 입구에 도착했습니다.');document.querySelector('#start').textContent='▶ 전투 시작';renderBoss();renderParty();renderSkills()}
function command(i){if(!running||cool[i]>0)return;if(i===0){if(!cast){toast('보스가 위험한 기술을 시전할 때 차단하세요.');return}if(!party.some(p=>p.hp>0&&['탱커','딜러'].includes(classes[p.c].role)))return;cast=null;cool[i]=party.some(p=>p.c===5&&p.hp>0)?10:15;log('차단 성공! 보스의 시전이 중단됩니다.');toast('차단 성공 · 파티가 위험을 넘겼습니다');bhp-=300}else if(i===1){if(!party.some(p=>p.hp>0&&classes[p.c].role==='힐러')){toast('생존한 힐러가 필요합니다.');return}party.forEach(p=>{p.debuff=0;if(p.hp>0)p.hp=Math.min(classes[p.c].hp,p.hp+280)});cool[i]=14;log('정화의 빛 · 저주를 해제하고 파티를 회복합니다.')}else if(i===2){if(party[0].hp<=0){toast('탱커가 쓰러져 보호를 사용할 수 없습니다.');return}shield=8;cool[i]=22;log('탱커의 보호막이 파티를 감쌉니다.')}else{buff=8;cool[i]=24;log('집중 공격! '+(adds.length?'소환된 적을 우선 공격합니다.':'보스의 약점을 공략합니다.'))}renderSkills()}
function dodge(){party.forEach((p,i)=>{if(p.hp<=0)return;let candidates=[[.2,.45],[.8,.45],[.2,.78],[.8,.78],[.5,.82],[.5,.5]];let safe=candidates.filter(v=>!zones.some(z=>Math.hypot(v[0]-z.x,v[1]-z.y)<z.r+.065));if(safe.length){const v=safe[i%safe.length];p.tx=v[0];p.ty=v[1]}});toast('전체 회피 명령 · 안전한 위치로 이동합니다')}
function damage(p,d){if(p.hp<=0)return;p.hp=Math.max(0,p.hp-d*(shield>0?.35:1));if(p.hp===0)log(classes[p.c].name+'이(가) 쓰러졌습니다.',true)}
let eventIndex=0;
function event(){eventIndex++;const type=eventIndex%4;if(type===1){cast={t:4,max:4};log('보스가 '+(bi===1?'독 폭발':bi===2?'공허 붕괴':'파멸의 포효')+'을 시전합니다!',true);toast('시전 경고 · Q로 차단하세요')}else if(type===2){for(let i=0;i<(phase===2?3:2);i++){const p=party[(i+eventIndex)%5];zones.push({x:p.x,y:p.y,r:bi===2?.15:.18,t:3.3,max:3.3})}log('위험 지대 생성 · 영웅을 이동시키세요.',true);toast('위험 범위 · A 전체 회피 / 전장 클릭 이동')}else if(type===3){const p=party.filter(p=>p.hp>0)[Math.floor(Math.random()*party.filter(p=>p.hp>0).length)];if(p)p.debuff=12;log('파티원에게 저주가 걸렸습니다. W로 해제하세요.',true)}else{adds.push({hp:1000+phase*300,x:.25,y:.35},{hp:1000+phase*300,x:.75,y:.35});log('망령이 소환되었습니다. 집중 공격으로 처리하세요!',true);toast('쫄 등장 · R 집중 공격으로 우선 처치')};if(bi===1&&type===2){party.filter(p=>p.hp>0).forEach(p=>p.debuff=Math.max(p.debuff,6));log('독의 정원 · 위험 범위와 독을 함께 처리하세요.',true)}if(bi===2&&type===1){zones.push({x:.5,y:.64,r:.2,t:3.7,max:3.7});log('붕괴와 동시에 중앙 균열이 열립니다.',true)}nextEvent=time+(phase===2?5.5:7)}
function finish(success){running=false;won=success;document.querySelector('#start').textContent='↻ 다시 도전';log(success?'공략 성공! 잿빛 성채에 빛이 돌아옵니다.':'파티 전멸 · 전술을 바꿔 다시 도전하세요.',!success);showModal(`<div style="font-size:45px;color:#cbb27a">${success?'♜':'⚔'}</div><h2>${success?'성채를 되찾았습니다':'원정은 아직 끝나지 않았습니다'}</h2><p>${bosses[bi].name} · ${fmt(time)}<br>${success?'다섯 영웅의 협력이 승리를 만들었습니다. 다음 보스에 도전하거나 새로운 클래스 조합을 시험해 보세요.':'위험 범위는 A로 회피하고, 시전은 Q로 차단하세요. 저주는 W로 해제할 수 있습니다. 전술 일시정지로 판단할 시간을 확보하세요.'}</p><button class="button primary" id="close-modal">전장으로 돌아가기</button>`)}
function update(dt){if(!running||paused)return;time+=dt;cool=cool.map(c=>Math.max(0,c-dt));buff=Math.max(0,buff-dt);shield=Math.max(0,shield-dt);party.forEach(p=>{p.x+=(p.tx-p.x)*Math.min(1,dt*2.5);p.y+=(p.ty-p.y)*Math.min(1,dt*2.5);if(p.debuff>0){p.debuff-=dt;damage(p,38*dt)}});const alive=party.filter(p=>p.hp>0),tank=alive.find(p=>classes[p.c].role==='탱커');if(tank)damage(tank,(phase===2?82:60)*dt);else alive.forEach(p=>damage(p,105*dt));const healer=alive.find(p=>classes[p.c].role==='힐러');if(healer){const target=alive.reduce((a,b)=>a.hp/classes[a.c].hp<b.hp/classes[b.c].hp?a:b);target.hp=Math.min(classes[target.c].hp,target.hp+(healer.c===3?88:108)*dt);if(healer.c===3)alive.forEach(p=>p.hp=Math.min(classes[p.c].hp,p.hp+12*dt))}let dps=alive.reduce((s,p)=>s+classes[p.c].dps,0)*(buff>0?2.8:1);if(adds.length){let aoe=alive.some(p=>p.c===7||p.c===6)?1.5:1;adds[0].hp-=dps*dt*aoe;alive.forEach(p=>damage(p,adds.length*9*dt));adds=adds.filter(a=>a.hp>0)}else bhp=Math.max(0,bhp-dps*dt);if(cast){cast.t-=dt;if(cast.t<=0){party.forEach(p=>damage(p,bi===2?570:450));cast=null;log('시전 완료 · 파티가 큰 피해를 받았습니다.',true)}}zones.forEach(z=>{z.t-=dt;if(z.t<=0)party.forEach(p=>{if(Math.hypot(p.x-z.x,p.y-z.y)<z.r)damage(p,680)})});zones=zones.filter(z=>z.t>0);const newPhase=bhp/bosses[bi].hp<.3?2:bhp/bosses[bi].hp<.65?1:0;if(newPhase!==phase){phase=newPhase;log('페이즈 '+(phase+1)+' · '+bosses[bi].phases[phase],true);toast('PHASE '+(phase+1)+' · '+bosses[bi].phases[phase]);document.querySelector('#tip').textContent=bosses[bi].mechanics[phase];renderBoss()}if(time>=nextEvent)event();if(time>=240){party.forEach(p=>damage(p,2000*dt));document.querySelector('#tip').textContent='광폭화! 시간이 초과되어 보스의 공격이 치명적입니다.'}if(bhp<=0)finish(true);else if(party.every(p=>p.hp<=0))finish(false)}
function showModal(html){document.querySelector('#modal-root').innerHTML=`<div class="overlay"><div class="modal">${html}</div></div>`;document.querySelector('#close-modal').onclick=()=>document.querySelector('#modal-root').innerHTML=''}
function formation(){if(running){toast('편성은 전투 종료 후 변경할 수 있습니다.');return}showModal(`<h2>파티 편성</h2><p>왼쪽에서 선택한 ${selected+1}번 영웅의 클래스를 변경합니다. 탱커 1명, 힐러 1명, 딜러 3명의 역할은 유지됩니다.</p><div class="class-grid">${classes.map((c,i)=>`<button class="class-choice" data-class="${i}" ${c.role!==classes[party[selected].c].role?'disabled':''}>${c.icon} ${c.name}<span>${c.role} · ${c.skill}</span><span>${c.desc}</span></button>`).join('')}</div><br><button class="button" id="close-modal">닫기</button>`);document.querySelectorAll('[data-class]').forEach(el=>el.onclick=()=>{party[selected]=makeMember(+el.dataset.class,selected);document.querySelector('#modal-root').innerHTML='';renderParty();log('파티 편성 변경 · '+classes[party[selected].c].name)})}
document.querySelector('#party-nav').onclick=formation;document.querySelector('#raid-nav').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});document.querySelector('#guide-nav').onclick=()=>showModal(`<h2>다섯 영웅을 지휘하는 방법</h2><p>기본 공격, 탱커의 어그로 유지, 힐러의 회복은 자동입니다. 지휘관은 기믹에 대응합니다.</p><p><b>Space</b> — 전술 일시정지. 시간을 멈춘 채 이동과 명령을 내릴 수 있습니다.<br><b>1–5</b> — 영웅 선택 및 해당 영웅을 따라가는 3쿼터 시점 전환.<br><b>방향키</b> — 선택한 영웅 이동. 전장 클릭으로 이동 명령도 가능합니다.<br><b>우클릭 드래그 / 휠</b> — 카메라 회전 / 확대. C로 기본 시점 복귀.<br><b>A</b> — 모든 영웅을 위험 범위 밖으로 이동시킵니다.<br><b>Q</b> — 보스의 위험한 시전을 차단합니다.<br><b>W</b> — 저주를 해제하고 파티를 회복합니다.<br><b>E</b> — 8초 동안 파티가 받는 피해를 줄입니다.<br><b>R</b> — 8초 동안 화력을 집중합니다. 소환된 적을 우선 처리합니다.</p><p>보스는 체력 65%, 30%에서 페이즈가 변합니다. 마지막 페이즈에서는 공격 주기가 빨라집니다. 4분 안에 처치하지 못하면 광폭화합니다. 클래스별 회복 방식, 차단 주기, 쫄 처리 능력이 다르므로 조합을 바꿔 도전하세요.</p><button class="button primary" id="close-modal">준비 완료</button>`);
document.querySelector('#start').onclick=()=>{if(running){toast('전투가 진행 중입니다. Space로 일시정지하세요.');return}reset();running=true;eventIndex=0;log('전투 시작 · 탱커가 보스의 시선을 끕니다.');document.querySelector('#start').textContent='⚔ 전투 진행 중';renderSkills()};function togglePause(){if(!running)return;paused=!paused;document.querySelector('#pause').innerHTML=paused?'▶ 전투 재개 <small>[Space]</small>':'Ⅱ 전술 일시정지 <small>[Space]</small>'}document.querySelector('#pause').onclick=togglePause;document.querySelector('#speed').onclick=()=>{speed=speed===1?2:1;document.querySelector('#speed').textContent=speed+'× 속도'};window.addEventListener('keydown',e=>{if(document.querySelector('.overlay'))return;if(e.code==='Space'){e.preventDefault();togglePause()}if('12345'.includes(e.key)){selected=+e.key-1;renderParty()}const n='qwer'.indexOf(e.key.toLowerCase());if(n>=0)command(n);if(e.key.toLowerCase()==='a'&&running)dodge()});function draw(){battle?.draw({party,selected,classes,bi,bhp,running,paused,time,cast,zones,adds,shield,buff})}
let renderAcc=0;function frame(now){let dt=Math.min(.1,(now-last)/1000)*speed;last=now;if(running&&!paused&&pressed.size&&party[selected].hp>0){const dx=Number(pressed.has('ArrowRight'))-Number(pressed.has('ArrowLeft')),dy=Number(pressed.has('ArrowDown'))-Number(pressed.has('ArrowUp'));const v=battle?.moveDirection(dx,dy)||{x:dx,y:dy};const p=party[selected];p.tx=Math.max(.13,Math.min(.87,p.x+v.x*.1));p.ty=Math.max(.39,Math.min(.85,p.y+v.y*.1))}update(dt);draw();renderAcc+=dt;if(renderAcc>.2){renderAcc=0;renderParty();renderSkills();document.querySelector('#boss-fill').style.width=bhp/bosses[bi].hp*100+'%';document.querySelector('#boss-health').textContent=`${Math.ceil(bhp).toLocaleString()} / ${bosses[bi].hp.toLocaleString()} HP`;document.querySelector('#timer').textContent=fmt(time)+' / 04:00';document.querySelector('#status').textContent=paused?'전술 일시정지':running?'전투 진행 중':won?'공략 완료':'출전 준비'}document.querySelector('#toast').classList.toggle('hidden',now>toastUntil);requestAnimationFrame(frame)}reset();requestAnimationFrame(frame);
