import { scaleFoe } from '../../../src/sim/grid/foes';
import { expect, it } from 'vitest';
import { freshMeta, settleRun } from '../../../src/sim/grid/meta';
import { newRunState } from '../../../src/sim/grid/runSetup';
import { placeDeathSuit } from '../../../src/sim/grid/deathSuit';
import { nextFloor, settleKills } from '../../../src/sim/grid/run';
import { GridSim } from '../../../src/sim/grid/gridSim';
import { newState } from '../../../src/sim/grid/state';
import { dist, same, type Room } from '../../../src/sim/grid/types';
import { handMap } from './kit';
const inside = (r: Room, p: { x: number; y: number }) => p.x >= r.x && p.x < r.x + r.w && p.y >= r.y && p.y < r.y + r.h;
const meta = (floor = 2, kind = 'minion') => ({ ...freshMeta(), suit: { floor, ids: ['dash', 'rapid'] as ('dash' | 'rapid')[], killer: { kind } } });

it('places only on the matching floor, at creation or descent, and once per run', () => {
  const m = meta();
  const s = newRunState(45, m, { gun: 'pistol', start: 1, startSuit: [] });
  expect(s.floorItems.some(f => f.item.kind === 'suit')).toBe(false);
  nextFloor(s);
  const suit = s.floorItems.find(f => f.item.kind === 'suit')!;
  expect(suit.item).toEqual({ kind: 'suit', ids: ['dash', 'rapid'], name: '남겨진 슈트' });
  expect(s.map.rooms.find(r => inside(r, suit.pos))).not.toEqual(s.map.rooms.find(r => inside(r, s.map.stairs!)));
  const n = s.foes.length;
  placeDeathSuit(s); expect(s.foes).toHaveLength(n);
  expect(s.floorItems.filter(f => f.item.kind === 'suit')).toHaveLength(1);
  nextFloor(s); expect(s.floorItems.some(f => f.item.kind === 'suit')).toBe(false);
  const opts = { gun: 'pistol', start: 6, startSuit: [] } as const;
  const a = newRunState(45, { ...meta(6), portals: [5], repairs: ['nav'] }, { ...opts, startSuit: [] });
  const b = newRunState(45, { ...meta(6), portals: [5], repairs: ['nav'] }, { ...opts, startSuit: [] });
  expect(a.floorItems).toEqual(b.floorItems);
  expect(a.foes).toEqual(b.foes);
  expect(a.floorItems.some(f => f.item.kind === 'suit')).toBe(true);
  expect(m.suit.ids).toEqual(['dash', 'rapid']);
});
it('chooses the farthest eligible room and free adjacent cells', () => {
  const map = handMap(['####################', ...Array.from({ length: 5 }, () => '#..................#'), '####################']);
  map.rooms = [{ x: 1, y: 1, w: 3, h: 4 }, { x: 8, y: 1, w: 3, h: 4 }, { x: 15, y: 1, w: 3, h: 4 }];
  map.stairs = { x: 16, y: 2 };
  const s = newState(map, 7);
  s.run.leftSuit = meta(1).suit;
  placeDeathSuit(s);
  const item = s.floorItems.find(f => f.item.kind === 'suit')!;
  expect(inside(map.rooms[1]!, item.pos)).toBe(true);
  expect(dist(s.foes[0]!.pos, item.pos)).toBe(1);
  expect(same(s.foes[0]!.pos, item.pos)).toBe(false);
});
it.each([['minion', 'minion'], ['champion', 'brute'], ['trap', 'minion']])('uses %s killer guardian %s, elite scaling, offer and remains', (killer, kind) => {
  const s = newRunState(5, meta(1, killer), { gun: 'pistol', start: 1, startSuit: [] });
  const guardian = s.foes.at(-1)!;
  expect(guardian.kind).toBe(kind);
  expect(guardian.elite).toBe(true);
  expect(guardian.power).toBeCloseTo(scaleFoe(guardian.kind as Exclude<typeof guardian.kind, 'hero'>, 1).power * 1.6);
  guardian.alive = false;
  settleKills(s, new Set([guardian.id]));
  expect(s.offers).toHaveLength(1);
  expect(s.floorItems.some(f => f.item.kind === 'material' && f.item.mat === 'remains' && same(f.pos, guardian.pos))).toBe(true);
});
it('walking onto the suit takes a turn, transmits it, and settlement clears the old suit', () => {
  const m = meta(1);
  const s = newRunState(5, m, { gun: 'pistol', start: 1, startSuit: [] });
  const item = s.floorItems.find(f => f.item.kind === 'suit')!;
  s.foes = []; s.traps = []; s.barrels = []; s.chests = [];
  s.map.stairs = undefined;
  s.hero.pos = { x: item.pos.x - 1, y: item.pos.y };
  s.map.tiles[s.hero.pos.y * s.map.w + s.hero.pos.x] = 'floor';
  const events = GridSim.fromState(s).act({ kind: 'move', dir: { x: 1, y: 0 }, plain: true });
  expect(s.time).toBe(1);
  expect(events).toContainEqual({ t: 0, type: 'suit', text: 'dash,rapid' });
  expect(s.run.recovered).toEqual(['dash', 'rapid']);
  expect(s.floorItems.some(f => f.item.kind === 'suit')).toBe(false);
  s.outcome = 'won';
  const result = settleRun(m, s);
  expect(result.startCandidates).toEqual([]);
  expect(result.tasted).toContain('dash');
  expect(result.energy).toBe(s.run.energy + 20);
  expect(result.suit).toBeUndefined();
  s.outcome = 'dead'; s.hero.suit = ['chain'];
  expect(settleRun(m, s).suit?.ids).toEqual(['chain']);
});
it('a new death replaces the old suit; an empty-handed death keeps the old one (it may lie where this run never went)', () => {
  const m = meta(8);
  const s = newRunState(5, m, { gun: 'pistol', start: 1, startSuit: [] });
  s.hero.suit = ['chain']; s.outcome = 'dead';
  expect(settleRun(m, s).suit).toEqual({ stones: [], materials: freshMeta().materials, floor: 1, ids: ['chain'], killer: { kind: 'self' } });
  s.hero.suit = [];
  const old = { ...m, suit: { floor: 3, ids: ['leap' as const], killer: { kind: 'minion' } } };
  expect(settleRun(old, s).suit).toEqual(old.suit);
});

it('arriving on the suit\'s floor says so', () => {
  const m = meta(8);
  m.suit = { floor: 2, ids: ['dash'], killer: { kind: 'minion' } };
  const s = newRunState(5, m, { gun: 'pistol', start: 1, startSuit: [] });
  s.events = [];
  nextFloor(s);
  expect(s.events.some((e) => e.type === 'suitHere')).toBe(true);
});
