import { stepped, type TextFn } from './traitTextUtil';

export const TEXT_ADVANCED: Record<string, TextFn> = {
  bloodHunger: (r) => `처치 → 최대 체력 ${10 * r}% 회복`,
  redFury: (r) => `위기 → 5턴간 피해 +${20 * r}%`,
  unyieldingShield: (r) => `막기 → 2칸 안 아군 보호막 ${5 * r}`,
  shieldThorns: (r) => `막기 → 공격자에게 피해 ${4 * r}`,
  breath: (r) => `제자리 3번째 공격 → 다음 공격 피해 +${stepped(200, 50, r)}%`,
  longSight: (r) => `사거리 +${r}`,
  trap: () => '빙결 부여 → 출혈',
  tracking: (r) => `적중 → ${20 * r}% 확률로 중독`,
  elementResonance: (r) => `원소 2종 이상 → 1칸 안 적 피해 ${6 * r}`,
  elementVeil: (r) => `상태 부여 → 보호막 ${3 * r}`,
  boneArmor: () => '소환수 생존 중 받는 피해 -20%',
  boneSeed: (r) => `궁극기 → 해골 소환 (최대 ${2 + r})`,
  divinePunish: () => '기절한 적에게 피해 2배',
  judgementEcho: (r) => `처치 → 1칸 안 적 피해 ${4 * r}`,
  lifeSpring: (r) => `보호막 파괴 → 체력 ${10 * r} 회복`,
  sharedLight: (r) => `궁극기 → 3칸 안 아군 치유 ${8 * r}`,
  execute: (r) => `적중 → ${stepped(20, 10, r)}% 확률로 체력 25% 미만 적 처형`,
  shadowHarvest: (r) => `처치 → 궁극기 대기 -${2 * r}턴`,
  poisonEssence: (r) => `중독 최대 중첩 +${3 * r}`,
  poisonSpread: (r) => `처치 → 1칸 안 적 중독 ${r}중첩`,
  bloodPact: () => '궁극기가 대기 대신 체력 30% 소모',
  shadowOath: () => '은신 중 턴당 체력 5% 회복, 은신 공격 3배',
  immortal: () => '죽을 피해 → 3턴 무적 (전투당 1회)',
  fanatic: () => '모든 발동 대기시간 절반',
  avatar: () => '적중 → 무작위 원소 부여',
  loneWolf: () => '2칸 안 아군 없으면 피해 +60%',
};
