import { stepped, top, type TextFn } from './traitTextUtil';

export const TEXT_CLASS: Record<string, TextFn> = {
  whirlwind: (r) => `포위 베기 대기 -${r}턴${top(r, '범위 2칸')}`,
  bloodBlade: () => '포위 베기 적중 → 출혈',
  shieldPro: (r) => `막기 확률 +${10 * r}%`,
  riposte: (r) => `응수 반격 피해 +${50 * r}%`,
  charge: () => '처치 → 3칸 안 적에게 돌진 후 베기',
  warEcho: (r) => `궁극기 → 아군 3턴간 피해 +${stepped(20, 10, r)}%`,
  rapid: (r) => `공격 속도 +${10 * r}%`,
  piercing: (r) => `치명 → 뒤의 적에게 피해 ${stepped(100, 25, r)}%`,
  steady: (r) => `정조준 최대치 +${30 * r}%`,
  huntMark: () => '만피 적 치명 → 표식',
  retreat: (r) => `물러난 직후 사격 피해 +${stepped(40, 20, r)}%`,
  arrowShower: (r) => `화살비 범위 +1${top(r, '화살 8발')}`,
  amplify: (r) => `원소 피해 +${15 * r}%`,
  quickChant: (r) => (r >= 2 ? '연쇄 주문 2번째 공격마다' : '2단계: 연쇄 주문 2번째 공격마다'),
  frostTouch: (r) => `적중 → ${stepped(20, 10, r)}% 확률로 냉기`,
  current: () => '화염구 → 감전',
  flow: (r) => `처치 → 궁극기 대기 -${r}턴`,
  combust: () => '화상 적 처치 → 1칸 안 적 화상',
  blessing: (r) => `치유량 +${30 * r}%`,
  quickPrayer: (r) => `구원의 손 대기 -${2 * r}턴`,
  warding: (r) => `축복 보호막 +${5 * r}`,
  retribution: (r) => `2칸 안 아군 피격 → 공격자에게 피해 ${4 * r}`,
  purify: () => '치유 → 대상 상태 이상 하나 해제',
  martyr: (r) => `위기 → 2칸 안 아군 치유 ${stepped(15, 10, r)}`,
  shadow: (r) => `잠행 은신 +${r}턴`,
  poisonBlade: (r) => `적중 → 중독 ${r >= 2 ? 2 : 1}중첩`,
  vital: (r) => `치명 확률 +${10 * r}%`,
  ambush: () => '은신 중 공격 피해 2배',
  smokescreen: () => '위기 → 1턴 은신, 붙은 적 명중 -50%',
  bladeDance: (r) => `처치 → 다음 공격 +${25 * r}%, 2칸 안 적에게 순간이동`,
};
