import { chromium } from '@playwright/test';
const out = process.argv[2], base = 'http://localhost:4173/PROJ_R/';
const br = await chromium.launch({ args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await br.newPage({ viewport: { width: 1280, height: 720 } });
p.on('pageerror', (e) => console.log('ERR', e.message));
await p.goto(`${base}?seed=3`); await p.click('[data-testid="to-grid"]', { timeout: 60000 });
await p.waitForSelector('.base-menu', { timeout: 60000 }); await p.waitForTimeout(6000);
await p.screenshot({ path: `${out}/base-mode.png` });
await p.mouse.move(640, 300); await p.mouse.down(); await p.mouse.move(400, 200, { steps: 8 }); await p.mouse.up(); await p.waitForTimeout(800);
await p.screenshot({ path: `${out}/base-pan.png` });
await br.close();
