import { chromium } from '@playwright/test';
const out = process.argv[2];
const b = await chromium.launch({ args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
p.on('pageerror', e => console.log('ERR', e.message));
await p.goto('http://localhost:5199/PROJ_R/?seed=3&lvl');
await p.getByText('깨어나기').click({ timeout: 60000 });
await p.waitForSelector('.wh-top', { timeout: 90000 });
await p.waitForTimeout(14000);
await p.screenshot({ path: `${out}/solo-world.png` });
console.log('skills', await p.locator('.wh-party .pf-skill kbd').allInnerTexts());
await p.keyboard.press('k');
await p.waitForTimeout(500);
await p.keyboard.press('c');
await p.waitForTimeout(800);
await p.screenshot({ path: `${out}/solo-stat.png` });
const q = await b.newPage({ viewport: { width: 1280, height: 720 } });
q.on('pageerror', e => console.log('ERR', e.message));
await q.goto('http://localhost:5199/PROJ_R/?demo=chains&seed=10');
await q.waitForSelector('.wh-top', { timeout: 90000 });
await q.waitForTimeout(6000);
await q.screenshot({ path: `${out}/solo-delve.png` });
console.log('beacon', await q.locator('[data-k="beacon"]').count(), await q.locator('[data-k="beacon"]').innerText().catch(() => '-'));
await b.close();
