import { expect, it } from 'vitest';
import { starterGear } from '../../src/sim/delve/gear';
import { damage, entOf, strike } from '../../src/sim/party/partyCore';
import { partyRoom, tick } from '../../src/sim/party/partySim';
import { useUltimate } from '../../src/sim/party/ultimate';
import { emit } from '../../src/sim/party/triggers';
import { applyStatus, statusMult } from '../../src/sim/party/status';
import { heal } from '../../src/sim/party/kitEffects';
const setup = () => { const p = partyRoom(); for (const u of p.units)
    if (u.cls)
        u.gear = starterGear(u.cls, () => u.id); const u = p.units[0]!, f = p.units[3]!; entOf(p, f.id)!.hp = entOf(p, f.id)!.maxHp = 500; entOf(p, f.id)!.pos = { x: 4, y: 4 }; return { p, u, f }; };
it('bait exposure lasts five seconds and foreign marks amplify attacks through the status engine', () => { const { p, u, f } = setup(); u.gear!.accessory = { id: 'a', def: 'baitCharm', power: 0 }; useUltimate(p, u.id); expect(f.status.exposed?.until).toBe(5); expect(statusMult(p, u, f, false, 0, [])).toBe(1.5); applyStatus(p, u, f, 'mark', 0, []); expect(statusMult(p, p.units[1]!, f, false, 0, [])).toBeCloseTo(1.95); });
it('guard links transfer once even if both allies wear one', () => { const { p } = setup(); const a = p.units[1]!, b = p.units[2]!; entOf(p, a.id)!.pos = { x: 3, y: 3 }; entOf(p, b.id)!.pos = { x: 3, y: 4 }; for (const u of [a, b])
    u.gear!.accessory = { id: u.id, def: 'guardOath', power: 0 }; const ah = entOf(p, a.id)!.hp, bh = entOf(p, b.id)!.hp; damage(p, 0, 'x', a, 10, []); expect(entOf(p, a.id)!.hp).toBe(ah - 7); expect(entOf(p, b.id)!.hp).toBe(bh - 3); });
it('echo responds only to another successful nearby ultimate and keeps stronger empowerment', () => { const { p, u } = setup(); const a = p.units[1]!; a.gear!.accessory = { id: 'a', def: 'echoCharm', power: 0 }; a.empower = 2.5; useUltimate(p, u.id); expect(a.empower).toBe(2.5); a.empower = 1; u.ultReady = 0; useUltimate(p, u.id); expect(a.empower).toBe(2); a.empower = 1; useUltimate(p, u.id); expect(a.empower).toBe(1); });
it('catalog hits heal actual damage, apply marks and work for ultimate strikes too', () => { const { p, u, f } = setup(); u.gear!.accessory = { id: 'a', def: 'vampireRing', power: 0 }; entOf(p, u.id)!.hp = 10; emit(p, 'hit', { t: 0, src: u, target: f, amount: 10, ev: [] }); expect(entOf(p, u.id)!.hp).toBe(12); u.gear!.accessory = { id: 'a', def: 'markRing', power: 0 }; p.s.rng.chance = c => c > 0; strike(p, u, f, 0, [], 1, false); expect(f.status.mark?.by).toBe(u.id); });
it('thorns can kill an attacking source without a later hit from that source', () => { const { p, u, f } = setup(); u.gear!.armor = { id: 'a', def: 'thornPlate', power: 0 }; entOf(p, f.id)!.hp = 1; p.s.rng.chance = c => c > 0; const ev: Parameters<typeof strike>[4] = []; strike(p, f, u, 0, ev); expect(entOf(p, f.id)!.alive).toBe(false); const death = ev.findIndex(e => e.type === 'die' && e.dst === f.id); expect(ev.slice(death + 1).some(e => e.type === 'hit' && e.src === f.id)).toBe(false); });
it('burn advances during idle simulation but paused time remains frozen', () => { const { p, u, f } = setup(); for (const x of p.units)
    x.nextAt = 100; applyStatus(p, u, f, 'burn', 0, []); const hp = entOf(p, f.id)!.hp; tick(p, 3); expect(entOf(p, f.id)!.hp).toBe(hp - 9); p.waiting = true; expect(tick(p, 10)).toEqual([]); expect(p.time).toBe(3); });
it('pilgrim relic heals splash holy damage around the healed ally', () => { const { p, u, f } = setup(); u.cls = 'cleric'; u.gear!.weapon = { id: 'a', def: 'pilgrimRelic', power: 0 }; entOf(p, u.id)!.hp = 1; const hp = entOf(p, f.id)!.hp; heal(p, u, u, 5, 0, []); expect(entOf(p, f.id)!.hp).toBe(hp - 5); });
it('the blood greatsword primes a double attack after killing a bleeding foe', () => { const { p, u, f } = setup(); u.gear!.weapon = { id: 'a', def: 'bloodGreat', power: 0 }; applyStatus(p, u, f, 'bleed', 0, []); damage(p, 0, u.id, f, 1000, []); expect(u.empower).toBe(2); });
it('berserker bracelet accelerates one attack; wind ring evades one hit after moving', () => { const { p, u, f } = setup(); u.gear!.accessory = { id: 'a', def: 'berserkBracelet', power: 0 }; emit(p, 'struck', { t: 0, src: u, target: f, ev: [] }); expect(u.fastNext).toBe(true); p.s.rng.chance = c => c > 0; strike(p, u, f, 0, []); expect(u.fastNext).toBe(false); u.gear!.accessory = { id: 'a', def: 'windRing', power: 0 }; emit(p, 'moved', { t: 0, src: u, ev: [] }); expect(u.dodgeNext).toBe(true); });
