import { afterEach, expect, it, vi } from 'vitest';
import { freshMeta } from '../../src/sim/grid/meta';
import { startGridRun, loadRun, continueGridRun } from '../../src/app/gridRun';
afterEach(() => vi.unstubAllGlobals());
it('launches ship selections, resumes, settles, and launches again with returned meta even without storage', () => {
  vi.stubGlobal('localStorage', { getItem: () => null, setItem: () => { throw Error(); }, removeItem: () => {} });
  const meta = freshMeta(); meta.rounds = ['shock']; meta.facilities.navCrypt = true;
  const run = startGridRun(33, { gun: 'pistol', round: 'shock', start: 6, startSuit: [] }, meta);
  expect(run.sim.s.run.floor).toBe(6); expect(run.sim.s.hero.gear.hands[0]?.group).toBe('pistol');
  run.sim.s.run.energy = 150; run.sim.s.outcome = 'dead'; run.checkpoint();
  expect(run.meta.energy).toBe(150);
  const next = startGridRun(34, { gun: 'pistol', round: 'shock', start: 6, startSuit: [] }, run.meta);
  expect(next.meta.energy).toBe(150);
  expect(next.sim.s.run.floor).toBe(6);
});
it('continues the saved run independently of new ship equipment selections', () => {
  const data = new Map<string, string>();
  vi.stubGlobal('localStorage', { getItem: (k: string) => data.get(k) ?? null, setItem: (k: string, v: string) => data.set(k, v), removeItem: (k: string) => data.delete(k) });
  const meta = freshMeta(); meta.rounds = ['fire']; meta.unlocked = ['counter'];
  startGridRun(9, { gun: 'pistol', round: 'fire', start: 1, startSuit: ['counter'] }, meta);
  expect(loadRun()?.hero.suit).toEqual(['counter']);
  expect(loadRun()?.hero.rounds).toEqual(['fire']);
  expect(continueGridRun()?.sim.s.hero.gear.hands[0]?.group).toBe('pistol');
});
it('resumes a legacy run without retrofitting its gear or suit', () => {
  const data = new Map<string, string>();
  vi.stubGlobal('localStorage', { getItem: (k: string) => data.get(k) ?? null, setItem: (k: string, v: string) => data.set(k, v), removeItem: (k: string) => data.delete(k) });
  startGridRun(9);
  const old = JSON.parse(data.get('projr.grid.run.v1')!);
  delete old.state.run.unlocked; delete old.state.run.tasted; delete old.state.hero.fx.free;
  old.state.hero.gear.hands[1] = null; old.state.hero.suit = ['rapid'];
  data.set('projr.grid.run.v1', JSON.stringify(old));
  const continued = continueGridRun()!;
  expect(continued.sim.s.hero.gear.hands[1]).toBeNull();
  expect(continued.sim.s.hero.suit).toEqual(['rapid']);
  expect(continued.sim.s.hero.fx.free).toBe(false);
  expect(() => continued.sim.act({ kind: 'wait' })).not.toThrow();
  continued.checkpoint();
  expect(loadRun()?.hero.suit).toEqual(['rapid']);
});
