import { expect, it } from 'vitest';
import { freshMeta, buy } from '../../src/sim/grid/meta';
import { stationLit } from '../../src/view/grid/stationLit';
import { panelContents, launchOptions, toggleStartSuit } from '../../src/ui/grid/ship/panelContents';
const setup = { gun: 'pistol', start: 1, startSuit: [] } as const;
const opts = () => ({ ...setup, startSuit: [] });
it('lights basic facilities and powers purchased areas', () => {
  const m = freshMeta();
  for (const id of ['pod', 'core', 'hatch', 'records'] as const) expect(stationLit(m, id)).toBe(true);
  for (const id of ['armory', 'suitlab', 'nav'] as const) expect(stationLit(m, id)).toBe(false);
  m.energy = 1000; m.bossesKilled = [5];
  for (const id of ['round:fire', 'chargePlus1', 'navCrypt']) buy(m, id);
  for (const id of ['armory', 'suitlab', 'nav'] as const) expect(stationLit(m, id)).toBe(true);
});
it('lists purchases with affordability, prerequisite and ownership gates', () => {
  const m = freshMeta();
  expect(panelContents(m, 'armory', opts()).choices.map(c => c.id)).toEqual(['plain']);
  expect(panelContents(m, 'armory', opts()).shop.every(c => !c.enabled)).toBe(true);
  m.energy = 1000;
  expect(panelContents(m, 'armory', opts()).shop.every(c => c.enabled)).toBe(true);
  expect(panelContents(m, 'nav', opts()).shop.every(c => !c.enabled)).toBe(true);
  m.bossesKilled = [5];
  expect(panelContents(m, 'nav', opts()).shop.map(c => c.enabled)).toEqual([true, false]);
  buy(m, 'navCrypt'); buy(m, 'round:fire');
  expect(panelContents(m, 'nav', opts()).choices.map(c => c.id)).toEqual(['1', '6']);
  expect(panelContents(m, 'armory', opts()).choices.map(c => c.id)).toEqual(['plain', 'fire']);
  expect(panelContents(m, 'armory', opts()).shop.some(c => c.id === 'round:fire')).toBe(false);
  expect(panelContents(m, 'suitlab', opts()).shop.slice(0, 4).map(c => c.enabled)).toEqual([true, false, true, false]);
});
it('describes records, candidates, energy, pod and hatch in Korean', () => {
  const m = freshMeta(); m.energy = 42; m.startCandidates = ['rapid'];
  expect(panelContents(m, 'records', opts()).lines).toHaveLength(4);
  expect(panelContents(m, 'records', opts()).lines[0]).toContain('돌진 베기');
  expect(panelContents(m, 'records', opts()).lines[0]).toContain('2칸');
  expect(panelContents(m, 'suitlab', opts()).lines).toEqual(['시작 각인 2칸 · 최대 충전 10']);
  expect(panelContents(m, 'core', opts(), 12).lines.join()).toContain('42');
  expect(panelContents(m, 'core', opts(), 12).lines.join()).toContain('12');
  expect(panelContents(m, 'pod', opts()).lines.join()).toContain('최고');
  expect(panelContents(m, 'hatch', opts()).lines.join()).toContain('권총');
  expect(panelContents(m, 'hatch', opts()).choices[0]?.enabled).toBe(true);
});
it('limits unlocked choices and clears shortcut engravings', () => {
  const m = freshMeta(); m.unlocked = ['dash', 'counter', 'flow'];
  const o = { gun: 'pistol', round: 'frost', start: 11, startSuit: ['dash', 'dash', 'chain', 'counter'] } as const;
  expect(launchOptions(m, { ...o, startSuit: [...o.startSuit] })).toEqual({ gun: 'pistol', round: 'plain', start: 1, startSuit: ['dash', 'counter'] });
  const selected = { ...opts(), startSuit: ['dash', 'counter'] as typeof m.unlocked };
  expect(panelContents(m, 'hatch', selected).choices.map(c => c.enabled)).toEqual([true, true, false]);
  expect(toggleStartSuit(m, selected, 'flow').startSuit).toEqual(['dash', 'counter']);
  expect(toggleStartSuit(m, selected, 'dash').startSuit).toEqual(['counter']);
  m.facilities.navRuins = true;
  expect(launchOptions(m, { ...o, startSuit: [...o.startSuit] }).startSuit).toEqual([]);
  expect(panelContents(m, 'hatch', { ...opts(), start: 11 }).choices).toEqual([]);
});
it('lists locked engravings with tasted prices and unlocked hatch choices', () => {
  const m = freshMeta(); m.energy = 60; m.tasted = ['flow']; m.startCandidates = ['rapid'];
  const shop = panelContents(m, 'suitlab', opts()).shop;
  expect(shop.find(e => e.id === 'engrave:flow')).toMatchObject({ label: '흐름 ⚡60', enabled: true });
  expect(shop.find(e => e.id === 'engrave:execute')).toMatchObject({ label: '처형 ⚡90', enabled: false });
  expect(shop.some(e => e.id === 'engrave:gunRelay')).toBe(false);
  const choices = panelContents(m, 'hatch', opts()).choices;
  expect(choices.map(e => e.id)).toEqual(m.unlocked);
  expect(choices.every(e => e.selected)).toBe(true);
});
it('offers only unlocked rounds, keeps the chosen round and falls back to plain', () => {
  const m = freshMeta(); m.energy = 500;
  expect(buy(m, 'round:fire')).toBe(true); expect(buy(m, 'round:shock')).toBe(true);
  const chosen = { ...opts(), round: 'fire' as const };
  expect(launchOptions(m, chosen).round).toBe('fire');
  expect(panelContents(m, 'armory', chosen).choices.filter(c => c.selected).map(c => c.id)).toEqual(['fire']);
  expect(panelContents(m, 'armory', chosen).choices.map(c => c.label)).toEqual(['기본탄', '화염탄', '전격탄']);
  expect(panelContents(m, 'armory', chosen).shop.map(c => c.id)).toEqual(['round:frost', 'round:poison']);
  expect(launchOptions(m, { ...opts(), round: 'poison' }).round).toBe('plain');
});
